all:
	ncc -out:"chalks.exe" -r:System.Runtime.Remoting.dll -pkg:glade-sharp-2.0 -pkg:gtk-sharp-2.0 -pkg:gtksourceview-sharp -res:chalks.glade -res:chalks.ico Chalks.n Gui.n ConcurrentEditionWidget.n ConcurrentEdition.n Network.n
